services:
  postgres:
    image: postgres:latest
    container_name: SE
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: SE
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    depends_on:
      - postgres

  server:
    container_name: kasian_phrom_server
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file: 
      - .env
    restart: on-failure