services:
  postgres:
    image: postgres:latest
    container_name: se
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: SE
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    depends_on:
      - postgres

  server:
    container_name: kasian_phrom_server
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SSL_MODE=disable
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - JWt_SECRET=${JWt_SECRET}
      - BUCKET_NAME=${BUCKET_NAME}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - RECOMMEND_API_URL=http://seai:8000
    restart: on-failure

  model:
    image: valhir/fastapi-app:latest
    container_name: seai
    ports:
      - "8000:8000"